# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/helix
spring.datasource.username=root
spring.datasource.password=Yearup2026

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Seed Data
spring.sql.init.mode=always
spring.jackson.serialization.fail-on-empty-beans=false